FROM python:3.12

RUN set -eux; \
    apt-get update && \
    apt-get install -y --no-install-recommends curl python3-dev && \
    curl -fsSL --proto '=https' https://install.python-poetry.org | python3 - && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-interaction --no-root

COPY . .

CMD bash -c "poetry run pytest ./tests > /logs/testlog.txt 2>&1"
