services:
  postgresql:
    image: postgres:15
    env_file: .env.test
    networks:
      - backend
    volumes:
      - postgresql:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    env_file: .env.test
    command:
      - --changelog-file=db.master-changelog.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    networks:
      - backend
    volumes:
      - ./db/migration:/liquibase/changelog

  api:
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.backend.coverage
    env_file: .env.test
    environment:
       - E2E_ACTIVE=TRUE
    networks:
      - backend
    volumes:
      - /tmp/booktrack:/app/coverage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 3s
      timeout: 3s
      retries: 10


  test_client:
    depends_on:
      api:
        condition: service_healthy
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.pytest
    networks:
      - backend
    volumes:
      - /tmp/booktrack:/logs


volumes:
  postgresql: { }

networks:
  backend: { }
